//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.16 at 06:28:10 PM NPT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.promostandards.org/WSDL/Inventory/2.0.0/SharedObjects/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.promostandards.wsdl.inventory._2_0_0.sharedobjects;
