package inventory;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.16 at 06:28:10 PM NPT 
//



import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QuantityUomType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QuantityUomType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="BX"/&gt;
 *     &lt;enumeration value="CA"/&gt;
 *     &lt;enumeration value="DZ"/&gt;
 *     &lt;enumeration value="EA"/&gt;
 *     &lt;enumeration value="KT"/&gt;
 *     &lt;enumeration value="PK"/&gt;
 *     &lt;enumeration value="PR"/&gt;
 *     &lt;enumeration value="RL"/&gt;
 *     &lt;enumeration value="SL"/&gt;
 *     &lt;enumeration value="ST"/&gt;
 *     &lt;enumeration value="TH"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "QuantityUomType")
@XmlEnum
public enum QuantityUomType {

    BX,
    CA,
    DZ,
    EA,
    KT,
    PK,
    PR,
    RL,
    SL,
    ST,
    TH;

    public String value() {
        return name();
    }

    public static QuantityUomType fromValue(String v) {
        return valueOf(v);
    }

}
